// 1. External / Framework Imports
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

// 2. Internal Components (Organized by atomic design if possible)
import Header from "@/components/organisms/Header";
import Footer from "@/components/organisms/Footer";

// 3. Global Styles (Always last so they can override component defaults)
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const PrimaryNavLinks = [
    { label: "About", href: "/about" },
    { label: "Projects", href: "/projects" },
    { label: "Contact", href: "/contact" },
  ];
  const FooterNavLinks: { label: string; href: string; target: "_blank" | "_self" }[] = [
    { label: "GitHub", href: "https://github.com", target: "_blank" },
    { label: "LinkedIn", href: "https://linkedin.com", target: "_blank" },
    { label: "Twitter", href: "https://twitter.com", target: "_blank"}
  ];
  return (
    <html lang="en">
      <body className="bg-black text-white">
        <Header content="Maze" links={PrimaryNavLinks} />
        <main className="max-w-5xl mx-auto px-6 py-12">
          {children}
        </main>
        <Footer content={`© ${new Date().getFullYear()} Maze`} links={FooterNavLinks} />
      </body>
    </html>
  );
}